steps:
 - id: "Store Values"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
    - "-c"
    - |
       echo "Inicio do processo"
       output_sensitive=$(grep IsSensitive vars.yaml)
       sensitive_value=${output_sensitive#*'IsSensitive : '}
       echo $sensitive_value > /workspace/validate_sensitive.txt
       output_function=$(grep Functions vars.yaml)
       functions_value=${output_function#*'Functions : '}
       echo $functions_value > /workspace/functions_name.txt
 - id: "Read Values"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
     - "-c"
     - |
         echo "Segundo do processo"
         echo $($_ENV)
         for val in $($_ENV); do
            echo $val
         done
substitutions:
  _ENV: "cat /workspace/validate_sensitive.txt"
