steps:
 - id: "Store Values"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
    - "-c"
    - |
       echo "Inicio do processo"
       output_sensitive=$(grep IsSensitive vars.yaml)
       sensitive_value=${output_sensitive#*'IsSensitive: '}
       echo $sensitive_value > /workspace/validate_sensitive.txt
       output_function=$(grep Functions vars.yaml)
       functions_value=${output_function#*'Functions: '}
       echo $functions_value > /workspace/functions_name.txt
 - id: "Get Is Sensitive"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
     - "-c"
     - |
         echo "Varifica se é sensitive"
         if $(cat /workspace/validate_sensitive.txt) = false;then
          echo "EEEH TRUE"
          echo $_SENSITIVEPATH > /workspace/path_project.txt
         else
          echo $_NONSENSITIVEPATH > /workspace/path_project.txt
         fi
 - id: "Execute Gcloud"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
     - "-c"
     - |
         echo "Executa GCLOUD"
         echo $(cat /workspace/path_project.txt)
         
         gcloud functions deploy ${_FUNCTION_9} --region=us-central1 --project=$(cat /workspace/path_project.txt) --source=./cloudfunction/${_FUNCTION_9} --trigger-http --entry-point=main --runtime=python39 --memory=2048MB --timeout=540 --set-env-vars=ENVIRONMENT=${_ENV}
         
         
substitutions:
  _FUNCTION_9: 'ingestao_raw-adyen_payments_accounting'
  _ENV: dev
  _SENSITIVEPATH: "rapid-strength-333817"
  _NONSENSITIVEPATH: "dataops-0001"
