steps:
- id: Build Repo Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-docker.pkg.dev/rapid-strength-333817/gcr.io/drapid-strength-333817/data-migration-labs-cicd/migration-pipeline', '.']

images:
   - us-docker.pkg.dev/rapid-strength-333817/gcr.io/drapid-strength-333817/data-migration-labs-cicd/migration-pipeline
