steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/ivan_test:latest', '.' ]
- name: 'gcr.io/$PROJECT_ID/ivan_test:latest'
  entrypoint: 'main'
images: [gcr.io/$PROJECT_ID/ivan_test:latest]
