steps:
 - id: "Store Values"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
    - "-c"
    - |
       echo "Inicio do processo"
       output=$(grep IsSentive vars.yaml)
       sensitive_value=${output#*'IsSentive:'}
       echo $sensitive_value > /workspace/validate_sensitive.txt
 - id: "Read Values"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
     - "-c"
     - |
         echo "Segundo do processo"
         echo $($_ENV)
         for val in $($_ENV); do
            echo $val
         done
substitutions:
  _ENV: "cat /workspace/first.txt"
