steps:
 - id: "Store Sensitve Validation"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
    - "-c"
    - |
       echo "Inicio do processo"
       output=$(grep IsSentitive vars.yaml)
       IsSentitive=${output#*'IsSentitive:'}
       echo $IsSentitive > /workspace/is_sentive.txt
 - id: "Store Functions Names"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
    - "-c"
    - |
       echo "Inicio do processo"
       output=$(grep IsSentitive vars.yaml)
       Functions=${output#*'Functions:'}
       echo $Functions > /workspace/functions.txt
 - id: "Read Values"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
     - "-c"
     - |
         echo "Segundo do processo"
         echo $($_SENSITIVE)
         for val in $($_SENSITIVE); do
            echo $val
         done
substitutions:
  _SENSITIVE: "cat /workspace/is_sentive.txt"
  
