steps:
- id: Build Repo Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/drapid-strength-333817/data-migration-labs-cicd/migration-pipeline', '.']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Exec Migration
  entrypoint: migration-pipeline
  args:
   - --env=dev
   - dataops
images:
   - gcr.io/drapid-strength-333817/data-migration-labs-cicd/migration-pipeline
