steps:
 - id: "Store Values"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
    - "-c"
    - |
       echo "Inicio do processo"
       output=$(grep IsSentive vars.yaml)
       IsSentive=${output#*'IsSentive: '}
       echo $IsSentive > /workspace/first.txt
 - id: "Read Values"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
     - "-c"
     - |
         echo "Segundo do processo"
         echo $($_IsSentive)
         for val in $($_IsSentive); do
            echo $val
         done
substitutions:
  _IsSentive: "cat /workspace/IsSentive.txt"
