steps:
 - id: "Store Values"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
    - "-c"
    - |
       echo "Inicio do processo"
       output_sensitive=$(grep IsSensitive vars.yaml)
       sensitive_value=${output_sensitive#*'IsSensitive : '}
       echo $sensitive_value > /workspace/validate_sensitive.txt
       output_function=$(grep Functions vars.yaml)
       functions_value=${output_function#*'Functions: '}
       echo $functions_value > /workspace/functions_name.txt
 - id: "Read Values"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
     - "-c"
     - |
         echo "Varifica se é sensitive"
         echo $($_VARSENSITIVE)
         
         if (($_VARSENSITIVE -eq True))
         then
          STATEMENTS1
         else
          STATEMENTS2
         fi
         
         for val in $($_VARSENSITIVE); do
            echo $val
         done
         
         echo $($_VARFUNCTIONS)
         for val in $($_VARFUNCTIONS); do
            echo $val
         done
         
substitutions:
  _VARSENSITIVE: "cat /workspace/validate_sensitive.txt"
  _VARFUNCTIONS: "cat /workspace/functions_name.txt"
  _SENSITIVEPATH: "ssbx-fds-prevencao-fraudes"
  _NONSENSITIVEPATH: "dataops-0001"
