steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          echo "Inicio do processo"
          output=$(grep valor1 vars.yaml)
          valor1=${output#*'valor1='}
          echo $valor1
          OIFS=${IFS}
          IFS="
          "
          export $_VAR1=$valor1
          
          echo $_VAR1
          
          
