steps:
 - id: "Py"
   name: 'gcr.io/google-appengine/python'
   entrypoint: "test.py"
 
 - id: "Store Values"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
    - "-c"
    - |
       echo "Inicio do processo"
       output=$(grep valor1 vars.yaml)
       valor1=${output#*'valor1='}
       echo $valor1 > /workspace/first.txt

 - id: "Read Values"
   name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: "bash"
   args:
     - "-c"
     - |
         echo "Segundo do processo"
         echo $($_ENV)
         echo $_ENV | wc -w
         for val in $($_ENV); do
            echo $val
         done
substitutions:
  _ENV: "cat /workspace/first.txt"
