steps:
 - name: 'python'
   args: ['pip3','install', '-r', 'requirements.txt', '--user']
 - name: 'python'
   args: ['python3','teste.py','--ENV=$_ENV','--SENSITIVEPATH=$_SENSITIVEPATH', '--NONSENSITIVEPATH=$_NONSENSITIVEPATH']
 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: 'bash'
   args: ['/workspace/run.sh']
         
substitutions:
  _ENV: dev
  _SENSITIVEPATH: "rapid-strength-333817"
  _NONSENSITIVEPATH: "dataops-0001"
