steps:
- id: Build Repo Image
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/rapid-strength-333817/data-migration-labs-cicd/migration-pipeline:dev', '.']
- name: us-central1-docker.pkg.dev/rapid-strength-333817/data-migration-labs-cicd/migration-pipeline:dev
  id: Exec Migration
  entrypoint: migration-pipeline
  args:
   - --env=dev
   - dataops
images:
   - us-central1-docker.pkg.dev/rapid-strength-333817/data-migration-labs-cicd/migration-pipeline:dev
