steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          echo "Inicio do processo"
          valor1=$(grep valor1 vars.yaml)
          valor1=${valor1#*'valor1='}
          echo $valor1
          export $valor1
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          echo "Segunda etapa do processo"
          echo $valor1
